/*______________ SKILL MIGRATION TABLE ________________*/
CREATE OR REPLACE TYPE T_skill_migration AS OBJECT (
  CODE VARCHAR2(3),
  NAME VARCHAR2(100),
  SKILL_GROUP_ID NUMBER(5),
  SKILL_GROUP_CATEGORY VARCHAR2(100),
  SKILL_GROUP_NAME VARCHAR2(60),
  NBR_MIGRANTS_X_10K FLOAT(4),
  MEMBER FUNCTION getCode RETURN VARCHAR2,
  MEMBER FUNCTION getName RETURN VARCHAR2,
  MEMBER FUNCTION getSkill_groupId RETURN NUMBER,
  MEMBER FUNCTION getSkill_groupCategory RETURN VARCHAR2,
  MEMBER FUNCTION getSkill_groupName RETURN VARCHAR2,
  MEMBER FUNCTION getSkill_NBR_MIGRANTS RETURN FLOAT

  );
/
CREATE OR REPLACE TYPE BODY  T_skill_migration AS
    MEMBER FUNCTION getCode  RETURN VARCHAR2 IS
    BEGIN
        RETURN CODE;
    END;
    MEMBER FUNCTION getName RETURN VARCHAR2 IS
    BEGIN
        RETURN Name;
    END;
    MEMBER FUNCTION getSkill_groupId RETURN NUMBER IS
    BEGIN
        RETURN SKILL_GROUP_ID ;
    END;
    MEMBER FUNCTION getSkill_groupCategory RETURN VARCHAR2 IS
    BEGIN
        RETURN  SKILL_GROUP_CATEGORY ;
    END;  
    MEMBER FUNCTION getSkill_groupName  RETURN VARCHAR2 IS
    BEGIN
        RETURN  SKILL_GROUP_NAME;
    END; 
    MEMBER FUNCTION getSkill_NBR_MIGRANTS RETURN FLOAT IS
    BEGIN
        RETURN  NBR_MIGRANTS_X_10K;
    END;    
END;
/
DROP TABLE tab_skill_migration;
CREATE TABLE tab_skill_migration OF T_skill_migration;
INSERT INTO tab_skill_migration SELECT * FROM I_bde_skill_migration;
commit;
/